### ISSUE TITLE
Allow Synchrony usage behind HTTPS-Proxy

### ISSUE THREAD

**Issue by kiview** [blacklabelops/confluence#2]
There is some buggy behavior in Confluence regarding Synchrony if run behind an HTTPS-Rerverse-Proxy:
https://jira.atlassian.com/browse/CONF-45264

If configuring the image with environment variable `CONFLUENCE_PROXY_SCHEME` as https, Confluence will deactivate the internal synchrony proxy (I'm not sure if this is a bug or by design?). This makes using the image behind a Traefik proxy impossible, if you want to use the collaborative editing feature.

So I'm not entirely sure if this is a problem of the image or a bug in Confluence, but I thought it useful to document this problem here.

**Comment by blacklabelops** [comment]
It's a Confluence issue. My environment variable just sets some config parameters inside Confluence's server.xml. The behavior is then triggered by Confluence itself.

Please take a look at my nginx configuration, it should help you with an alternative Traefik setup:

~~~~
location /synchrony {
          set $backend "http://confluence:8091";
          proxy_pass $backend;
          proxy_redirect http://confluence:8091 $scheme://$host/;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }


location / {
          set $backend "http://confluence:8090";
          proxy_pass $backend;
          proxy_redirect http://confluence:8090 $scheme://$host/;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
~~~~

You can setup two reverse proxies! One for confluence and one for synchrony. The synchrony reverse proxy will be forwarded to the synchrony port and is therefore not dependent on the internal Confluence proxy.

In my example the /synchrony reverse proxy must be defined before the root path /. Otherwise all would be matched against / and routed to 8090.

Hope this helps.

**Comment by kiview** [comment]
I'm not entirely sure if this would work with Traefik, since Traefik simply autodiscovers the running docker containers and makes them accessible via subdomains. I'm not sure if Traefik supports mixing of backends (this would be a docker backend and a manual, rule based backend in this case).

Maybe it would work if I setup an additional nginx proxy between Traefik and Confluence, which would be configured like you suggested.

I hope Atlassian will make the deactivation of the internal proxy configurable, this would eliminate this problem as well.

**Comment by blacklabelops** [comment]
This is already possible. You can edit the confluence.cfg.xml inside the confluence home directory.

You can edit the xml like this:

~~~~
$ docker exec -it confluence bash
$ vi confluence.cfg.xml
~~~~

You have to consult the Atlassian documentation on which properties symphony uses! I have seen it somewhere. You can enable the proxy and change symphony server ports.

**Comment by kiview** [comment]
Thx, I did not knew about this. I will look into this tomorrow and if I find a working solution, we might be able to make this configurable via environment variables?

**Comment by blacklabelops** [comment]
Please test if the setting will solve your problem, afterwards I can provide an image where you can set those setting through environment variables.

**Comment by kiview** [comment]
Sadly this does not work. I've already had this property set to `true`. 
Confluence will always try access synchrony via `/synchrony` instead of `/synchrony-proxy` once it detects a proxy configuration inside the `server.xml`.

So I'd say this is an Confluence upstream bug. I'm still communicating with Atlassian about this problem inside a support ticket, maybe I'll get further insights soon.

**Comment by kiview** [comment]
This was the bug ticket that was created after filing this bug at Atlassian:
https://jira.atlassian.com/browse/CONF-45264

It has been closed in release 6.0.2, as well as some other synchrony related stuff. This might be worth a try.

**Comment by ddean4040** [comment]
Worked through this and wanted to share that the proxy does need to be enabled as a system property in `setenv.sh`.

An image that would let us set properties through env vars would be amazing. Right now I'm mounting a volume to `<confluence install>/bin` to persist the change. That's enough to enable collaborative editing behind Traefik and no intermediate nginx proxy is needed.

This ticket has the string for enabling the proxy under "Workaround": https://jira.atlassian.com/browse/CONF-45728

**Comment by kiview** [comment]
Great that you've found a workaround, we still aren't using synchrony because of this problem.
I'm no entirely sure, but wouldn't it be enough to set the `CATALINA_OPTS` value as a real environment variable, since Tomcat injects this system environment variable into its context?

**Comment by blacklabelops** [comment]
Okay, envs for setting properties inside confluence.cfg.xml. Im right on it!

**Comment by blacklabelops** [comment]
Workaround:

~~~~
$ docker run -d -p 80:8090 -p 8091:8091 \
    --name confluence \
    -e "CATALINA_OPTS=-Dsynchrony.proxy.enabled=true -Xms1g -Xmx2g" \
    blacklabelops/confluence
~~~~

**Comment by blacklabelops** [comment]
Can please someone check the feature?

Feature available in new development image: blacklabelops/confluence:development.

[Readme](https://github.com/blacklabelops/confluence/tree/development#confluence-configuration-properties)

Example:

~~~~
$ docker run -d -p 80:8090 -p 8091:8091 \
    --name confluence \
    -e "CONFLUENCE_CONFIG_PROPERTY1=synchrony.proxy.enabled" \
    -e "CONFLUENCE_CONFIG_VALUE1=true" \
    blacklabelops/confluence:development
~~~~

**Comment by kiview** [comment]
I'll try it monday at work ASAP.

**Comment by blacklabelops** [comment]
Thanks, that's awesome!

**Comment by kiview** [comment]
Did not work for me, Confluence still trying to access `synchrony/resources/js/vendor/sockjs.min.js` instead of using `synchrony-proxy/resources/js/vendor/sockjs.min.js`.

This is my environment config:

```
services:
  confluence:
    image: blacklabelops/confluence:development
    container_name: confluence
    restart: always
    ports:
      - "8091:8091"
    labels:
      - "traefik.docker.network=traefik_default"
      - "traefik.port=8090"
    networks:
      - default
      - traefik_default
    volumes:
      - confluencedata:/var/atlassian/confluence
      - /opt/keystore/cacerts:/opt/java/jre1.8.0_92/lib/security/cacerts
    environment:
      - 'CATALINA_OPTS= -Xms256m -Xmx2g'
      - 'CONFLUENCE_DELAYED_START='
      - "CONFLUENCE_PROXY_NAME=confluence.${DOMAIN_NAME}" 
      - "CONFLUENCE_PROXY_PORT=443" 
      - "CONFLUENCE_PROXY_SCHEME=https" 
      - "CONFLUENCE_CONFIG_PROPERTY1=synchrony.proxy.enabled"
      - "CONFLUENCE_CONFIG_VALUE1=true"
```
