### ISSUE TITLE
Java VM limits should match (per Atlassian recommendation)

### ISSUE THREAD

**Issue by rwarren** [blacklabelops/confluence#50]
The current blacklabelops `docker-compose.yaml` Java VM settings are as follows:
```
    environment:
      - 'CATALINA_OPTS= -Xms256m -Xmx1g'
```
The Atlassian recommendations on [this page](https://confluence.atlassian.com/doc/managing-application-server-memory-settings-32899336.html) state:

> In the general case, both Jira & Confluence users will benefit from setting the minimum and maximum values identical

So it seems that this should be changed to:

```
    environment:
      - 'CATALINA_OPTS= -Xms1g -Xmx1g'
```

Same applies to the JIRA config... although (for JIRA) I do wonder at the blacklabelops default Xmx value of 1 GB, when the [general guidance from Atlassian themselves](https://confluence.atlassian.com/adminjiraserver/increasing-jira-application-memory-938847654.html) is:

> Granting Jira applications too much memory can impact performance negatively, so it is best to start with 768 MB, and make modest increases as necessary
 
Bumping to 1 GB seems reasonable to me, but... Java isn't my thing (thankfully) and I'm wary of direct guidance saying not to allocate too much!

**Comment by ckotte** [comment]
The docker-compose.yml needs to be adjusted. You need to specify _CATALINA_PARAMETER1_, _CATALINA_PARAMETER_VALUE1_, and so on to set the _CATALINA_OPTS_. 

For Jira it's _JVM_MINIMUM_MEMORY_ and _JVM_MAXIMUM_MEMORY_.

The default configuration if you don't specify additional environment variables:

Product| Java VM Settings
------------ | -------------
Confluence | -Xmx1024m -Xms1024m
Jira | -Xms384m -Xmx768m

**Comment by blacklabelops** [comment]
Jira Image is configured differently. This changed recently: https://github.com/blacklabelops/jira#a-word-about-memory-usage

**Comment by rwarren** [comment]
I'm confused.

1. Are the `JVM_xxx_MEMORY` settings _a replacement for_ `CATALINA_OPTS` or _in addition to_ `CATALINA_OPTS`?
1. Does this change only apply for recent JIRA versions, or is it an issue with the container?

Also, per the original reason for this issue, [their docs](https://confluence.atlassian.com/doc/managing-application-server-memory-settings-32899336.html) still say to set the min and max the same.

To cover off possible versioning issues, is this how the environment section should look like for these vars in the docker compose file?

```
    environment:
      JIRA_DATABASE_URL: <snip>
      JIRA_DB_PASSWORD: <snip>
      CATALINA_OPTS: -Xms1024m -Xmx1024m
      JVM_MINIMUM_MEMORY: 1024m
      JVM_MAXIMUM_MEMORY: 1024m
```

**Comment by ckotte** [comment]
Looks like Jira uses the JAVA_OPTS environment variable. You can check this in /opt/jira/bin/setenv.sh in the Docker container.

You need to specify:
```
environment:
      JIRA_DATABASE_URL: <snip>
      JIRA_DB_PASSWORD: <snip>
      SETENV_JVM_MINIMUM_MEMORY: 1024m
      SETENV_JVM_MAXIMUM_MEMORY: 1024m
```
